### ISSUE TITLE
Async call timeout exceeded. Timeout 100

### ISSUE THREAD

**Issue by facundofierro** [Telegram-Mini-Apps/tma.js#215]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [X] Telegram for Android
- [ ] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

I am having situations on initialization getting this error: **"Async call timeout exceeded. Timeout 100"**
The same miniapp is working fine in other devices but specially in an android phone I have 2 telegram user and trying switching between them and getting that error 90% of the time when opening the application.
In other devices, the application is always opening fine with the same users.

The application is done with next.js, so I am doing async loading.
```jsx
'use client'

import type { PropsWithChildren } from 'react'
import { SDKProvider } from '@tma.js/sdk-react'

export function TmaSDKLoader({ children }: PropsWithChildren) {
  return (
    <SDKProvider
      options={{
        cssVars: true,
        acceptCustomStyles: true,
        async: true,
      }}
    >
      {children}
    </SDKProvider>
  )
}
```

## To Reproduce

Do loading process and show error result:
`  const { loading, initResult, error } = useSDKContext()`

## Expected behavior
Expected to obtain a value on initResult when loading finishes.

**Comment by heyqbnk** [comment]
Did I get it right, that sometimes applications runs successfully and you don't see any errors? And it is only in the Android version of Telegram? This is rather strange, that 100ms is not enough to retrieve the viewport information, but who knows how Android application works

**Comment by facundofierro** [comment]
> Did I get it right, that sometimes applications runs successfully and you don't see any errors? And it is only in the Android version of Telegram? This is rather strange, that 100ms is not enough to retrieve the viewport information, but who knows how Android application works

Yes, I think to reproduce is to use with next.js 14 (because do SSR and need async option) and test on Android.
I would say 90% of the time I got that error on android accounts, so it is very easy to see it.
I am testing with many users and always work fine on iphone, ipad, web telegram, telegram app, ... I only see the issue in Android.

Do you think I can tweak this timeout somewhere in the code, so I can help to test?

**Comment by heyqbnk** [comment]
Unfortunately, I don't have an Android device and it seems like you have to test the possible solution by yourself.

To solve the problem, we could try increasing the viewport information request timeout at this [line](https://github.com/Telegram-Mini-Apps/tma.js/blob/master/packages/sdk/src/init/creators/createViewport.ts#L108).

Do you use the official Telegram application for Android, right? As far as I know, there are 2 of them in the store

**Comment by facundofierro** [comment]
Yes, I use the official version and also tried other 4 accounts (friends and family), and same user works fine on iphone.
Also works fine doing initialization without using this library. 
I am trying to test now ...

**Comment by heyqbnk** [comment]
To check if retrieving viewport information takes really long time, you could try using this code:

```typescript
import { useEffect } from 'react';
import { requestViewport } from '@tma.js/sdk';

function MyComponent() {
  useEffect(() => {
    console.time('request');
    requestViewport({ timeout: 5000 }).then(() => {
      console.timeEnd('request');
    });
  }, []);

  return null;
}
```

**Comment by Mergemat** [comment]
same on ios

**Comment by facundofierro** [comment]
@heyqbnk Sorry I got a bit stuck, I am deploying in Vercel and getting some errors related with Vite. Probably because of mixing vite and next.js projects.

Could you please publish a beta version of the package with that change? So I can test.
`npm publish --tag beta`

**Comment by facundofierro** [comment]
And if we have a beta release, maybe @Mergemat can test also his scenario.

**Comment by heyqbnk** [comment]
I am currently working on several things:
1. Increase timeout for viewport creation to make sure, code has enough time to retrieve its data.
2. Log how much time it took to perform some request. Then, we will know if some request took too much time.

Update will be available in the next several days, so you could try it

**Comment by facundofierro** [comment]
Sounds great

![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/53464671/26243a7c-15c7-4f4f-b9ba-aa8f47806ea6)

Is it that call?

**Comment by heyqbnk** [comment]
I have released a new update for SDK. It increased Viewport creation timeout to 5000 to make sure code has enough time to perform the request. In case this is not enough, it means, something is wrong outside of SDK.

Let me know about the results, please

**Comment by facundofierro** [comment]
Oh! 
I am still having the error most of the time, but now saying 5000 as timeout.
Weird!
I am thinking, what if you enabled to pass a parameter for that timeout, so I can make more extensive tests and see if there is some value that works fine or there is something else like the response never returning.
Sometimes works, randomly, but most of the time I got the error.

**Comment by facundofierro** [comment]
On telegram desktop, and iPad is working 100% well

**Comment by facundofierro** [comment]
And actually waiting 5 seconds is already slow, I see the loading screen these 5 seconds.
Another thing is that on this rare situations that is loading correctly in android, it is fast, it is not waiting these 5 seconds.
So I tend to think that the response is never happening.
Maybe the requestViewport is happening before something else required is not yet ready?
Maybe we could try to lower again the timeout and make 1 retry ....
Or if you are able enabled as parameter, timeout and retry, I can do multiple tests and give you the results.

**Comment by heyqbnk** [comment]
In case, application is not responding for 5 seconds, it means something is wrong with the application itself. I don't think increasing this timeout will change anything as long as this request is local between web and Telegram applications. It usually takes several milliseconds to be completed.

Check if you are not using the SDK from Telegram, because it conflicts with @tma.js. No wonder if the problem is in the Telegram for Android. Almost each Telegram application has its own problems even implementing basic Telegram Mini Apps functionality.

In case problem is stable, you could try calling `requestViewport` function and check if it completes. I mean, without using Next JS or anything else. Just pure `requestViewport` function. If some of the calls fails, something is surely wrong with the Telegram application. 

To simplify the process, you could serve basic HTML page and use [@tma.js/sdk UMD version](https://cdn.jsdelivr.net/npm/@tma.js/sdk). SDK will be accessible via `window.tmajs.sdk`  value

**Comment by heyqbnk** [comment]
Here is the HTML you could try:
```html
<html>
<head>
  <meta charset="UTF-8">
  <meta
    name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
  >
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Telegram Mini Apps TypeScript Example</title>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/@tma.js/sdk"></script>
  <script>
    const { requestViewport, retrieveLaunchData } = window.tmajs.sdk;

    requestViewport({ timeout: 1000 })
      // Viewport received.
      .then(() => alert('Success'))
      // Something went wrong. Display error and collect platform. This will probably
      // be useful.
      .catch((e) => {
        alert(`Failed: ${e.message}. Platform: ${retrieveLaunchData().launchParams.platform}`);
      });
  </script>
</body>
</html>
```

I have added platform name in the output so we could know which platform identifier fails. This will probably be useful for me

**Comment by facundofierro** [comment]
Vlad, I've found the problem. Yes was a conflicting library and the telegram-web-app.js was loaded twice. 
So it is working fine with next.js, no issue on that.
Thanks for taking care of this.

**Comment by heyqbnk** [comment]
> Is there any way to achieve that with this library?

I don't think so. The problem is how Telegram developers implemented Mini App and Telegram application communication. It doesn't allow us to properly use both of the packages at the same time.

Well, you shouldn't use both of the packages in the same application. This is something like using Vue along with React simultaneously

**Comment by facundofierro** [comment]
Yes that's reasonable.
But you think that with this library there is a way to open a telegram link? 
To do the same as this: window?.Telegram?.WebApp?.openTelegramLink('')
Maybe nos supported?

As I am understanding, this library does not use telegram official script?
 https://telegram.org/js/telegram-web-app.js 
 
I did now an ugly workaround, loading the script dynamically from javascript at the last moment, just to open the link and I close the miniapp.

**Comment by heyqbnk** [comment]
Yes, it supports all features from the Telegram SDK and much more.

Opening Telegram link:

https://docs.telegram-mini-apps.com/packages/typescript/tma-js-sdk/components/utils#opentelegramlink

In you case you are still choosing between these 2 TMA packages, take a look at Telegram SDK problems:

https://github.com/Telegram-Mini-Apps/tma.js#why-not-telegram-sdk

**Comment by heyqbnk** [comment]
As for know, I am closing this issue. Let me know if I can do something for you.
